#! /bin/csh

# Set the LEPHAREDIR and LEPHAREWORK variables automatically to defaults
export LEPHAREDIR=$(python -c "import lephare as lp; print(f'{lp.LEPHAREDIR}')" | tail -n 1) # use tail to ignore the on-import print statement
export LEPHAREWORK=$(python -c "import lephare as lp; print(f'{lp.dm.LEPHAREWORK}')" | tail -n 1) # use tail to ignore the on-import print statement
# Maximum number of threads. Don't put more than available. It could result in a strange behaviour of the code.
# export OMP_NUM_THREADS='20' 

 
#############
##  LIBRARY

# Take the two parameter files which could be configured
cp $LEPHAREDIR/examples/COSMOS.para .
cp $LEPHAREDIR/examples/output.para .

# Read the filters and compile them within one file stored in $WORK/filt
filter -c COSMOS.para
# Read a second set of filters which could be used to compute predicted magnitudes in some bands not present in the dataset (useful to simulate data)
filter -c COSMOS.para  --FILTER_LIST euclid/EUC_riz.lowres,euclid/EUC_Y.lowres,euclid/EUC_J.lowres,euclid/EUC_H.lowres --FILTER_CALIB 0 --FILTER_FILE filter_add

# Generate the library of predicted magnitudes for galaxy templates
# Case of the COSMOS templates used in Ilbert 2013
# Read the galaxy templates and store them in $WORK/lib_bin
sedtolib -c COSMOS.para -t G --GAL_SED $LEPHAREDIR/examples/COSMOS_MOD.list  --GAL_LIB LIB_VISTA 
# Use the galaxy templates + filters to derive a library of predicted magnitudes and store in $WORK/lib_mag
# Generate emission lines correlated to UV light + free factor in scaling the lines by a factor 2 
mag_gal  -c COSMOS.para -t G --GAL_LIB_IN LIB_VISTA --GAL_LIB_OUT VISTA_COSMOS_FREE --MOD_EXTINC 18,26,26,33,26,33,26,33  --EXTINC_LAW SMC_prevot.dat,SB_calzetti.dat,SB_calzetti_bump1.dat,SB_calzetti_bump2.dat  --EM_LINES EMP_UV  --EM_DISPERSION 0.5,1.,1.5
# Generate emission lines correlated to UV light + no free factor in scaling the lines 
mag_gal  -c COSMOS.para -t G --GAL_LIB_IN LIB_VISTA --GAL_LIB_OUT VISTA_COSMOS --MOD_EXTINC 18,26,26,33,26,33,26,33  --EXTINC_LAW SMC_prevot.dat,SB_calzetti.dat,SB_calzetti_bump1.dat,SB_calzetti_bump2.dat --EM_LINES EMP_UV  --EM_DISPERSION 1.

# Generate the library of predicted magnitudes for stars
# Read the stellar templates and store them in $WORK/lib_bin
sedtolib -c COSMOS.para -t S --STAR_SED $LEPHAREDIR/examples/STAR_MOD_ALL.list
# Use the stellar templates + filters to derive a library of predicted magnitudes and store in $WORK/lib_mag
mag_gal -c COSMOS.para -t S --LIB_ASCII YES --STAR_LIB_OUT ALLSTAR_COSMOS 

# Generate the library of predicted magnitudes for AGN templates
# AGN from Salvato 2009
# Read the AGN templates and store them in $WORK/lib_bin
sedtolib -c COSMOS.para -t Q --QSO_SED  $LEPHAREDIR/examples/AGN_MOD.list
# Use the AGN templates + filters to derive a library of predicted magnitudes and store in $WORK/lib_mag
mag_gal -c COSMOS.para -t Q --MOD_EXTINC 0,1000  --EB_V 0.,0.1,0.2,0.3 --EXTINC_LAW SB_calzetti.dat --LIB_ASCII NO



###################################################
# PHOTOMETRIC REDSHIFTS
###################################################


# Compute the photo-z and derive the adapation of the zero-points
zphota -c COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in --CAT_OUT zphot_vista_adapt.out --ZPHOTLIB VISTA_COSMOS_FREE,ALLSTAR_COSMOS,QSO_COSMOS  --ADD_EMLINES 0,100 --AUTO_ADAPT YES  


# Compute the photo-z without the adapation of the zero-points and applying the shifts given in keyword
# Assume that shifts are derived previously. Shifts will be substracted to apparent magnitudes and to be used later using  --APPLY_SYSSHIFT $SHIFT (to avoid rerunning auto-adapt)
export SHIFT="0.043748,-0.019692,-0.063787,-0.073428,-0.039337,-0.035061,-0.060209,-0.013895,0.001024,0.049628,-0.022248,0.063049,0.044423,0.024456,0.021558,0.039796,0.073169,0.008136,-0.161524,0.034896,0.039352,0.056378,0.039695,0.018222,0.061208,0.034747,0.011627,0.007835,0.000000,0.000000"
zphota -c COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in  --CAT_OUT zphot_vista_shift.out --ZPHOTLIB VISTA_COSMOS_FREE,ALLSTAR_COSMOS,QSO_COSMOS   --ADD_EMLINES 0,100 --AUTO_ADAPT NO --APPLY_SYSSHIFT $SHIFT --PDZ_OUT zphot_vista_shift --PDZ_TYPE BAY_ZG

# Test with no emission lines
zphota -c COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in  --CAT_OUT zphot_vista_noline.out --ZPHOTLIB VISTA_COSMOS_FREE,ALLSTAR_COSMOS,QSO_COSMOS  --ADD_EMLINES 0,0 --AUTO_ADAPT NO --APPLY_SYSSHIFT $SHIFT

# Test with no offsets from auto-adapt
zphota -c COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in  --CAT_OUT zphot_vista_noadapt.out --ZPHOTLIB VISTA_COSMOS_FREE,ALLSTAR_COSMOS,QSO_COSMOS   --ADD_EMLINES 0,100 --AUTO_ADAPT NO 

# Extract Id*.spec and Id*.chi for few sources
zphota -c COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in  --CAT_OUT zphot_vista_select.out --ZPHOTLIB VISTA_COSMOS_FREE,ALLSTAR_COSMOS,QSO_COSMOS   --ADD_EMLINES 0,100 --AUTO_ADAPT NO --APPLY_SYSSHIFT $SHIFT --PDZ_OUT NONE --PDZ_TYPE BAY_ZG --CAT_LINES 12000,12010 --SPEC_OUT YES 

# FIGURES
# Diagnostics on the photo-z quality
# results in figuresLPZ.pdf
python $LEPHAREDIR/examples/figuresLPZ.py zphot_vista_adapt.out

# Plot the best-fit templates
# Results in MULTISPEC.pdf
python $LEPHAREDIR/examples/spec.py Id*spec -d pdf



###################################################
# PHYSICAL PARAMETERS
###################################################

# Take the two parameter files which could be configured
cp $LEPHAREDIR/examples/output_mass.para .


# Generate the library of predicted magnitudes for galaxy templates to be used for physical parameters
# BC03 library 
# Library to derive physical parameters 
# Read the galaxy BC03 templates and store them in $WORK/lib_bin
sedtolib -c COSMOS.para -t G --GAL_SED $LEPHAREDIR/examples/BC03COMB_MOD.list --GAL_LIB LIB_COMB --SEL_AGE $LEPHAREDIR/examples/AGE_BC03COMB.dat
# Use the galaxy BC03 templates + filters to derive a library of predicted magnitudes and store in $WORK/lib_mag
# Example with a larger dz=0.03 step to save speed
# Use the "physical" recipes to generate the lines
# Add the dust component with one template of Bethermin+12
mag_gal  -c COSMOS.para -t G --GAL_LIB_IN LIB_COMB  --GAL_LIB_OUT BC03_COSMOS  --MOD_EXTINC 0,12,0,12,0,12 --EXTINC_LAW SB_calzetti.dat,extlaw_0.9.dat,salim18.dat --EB_V 0.,0.1,0.2,0.3,0.4,0.5,0.6,0.7 --Z_STEP 0.03,0,6 --EM_LINES PHYS --EM_DISPERSION 1 --ADD_DUSTEM YES

# Derive the stellar masses. Can be done with BC03 templates.
zphota -c COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in  --CAT_OUT masses.out --ZPHOTLIB BC03_COSMOS  --ADD_EMLINES 0,100 --AUTO_ADAPT NO --APPLY_SYSSHIFT $SHIFT  --ZFIX YES --PARA_OUT output_mass.para

# FIGURES
# Diagnostics on the physical parameter quality
# results in figuresLPP.pdf
python $LEPHAREDIR/examples/figuresLPP.py masses.out



######################################
#  Far IR
#######################################################


# another example of parameter file
cp $LEPHAREDIR/examples/HERSCHEL.para .

# Filters including the FIR
filter -c HERSCHEL.para

#IR library from Dale
sedtolib -c HERSCHEL.para -t G --GAL_SED $LEPHAREDIR/examples/DALE.list  --GAL_LIB LIB_DALE 
mag_gal  -c HERSCHEL.para -t G --GAL_LIB_IN LIB_DALE  --GAL_LIB_OUT DALE_COSMOS --MOD_EXTINC 0,0

# BC03 SED
sedtolib -c HERSCHEL.para -t G --GAL_SED $LEPHAREDIR/examples/BC03COMB_MOD.list --GAL_LIB LIB_BC03CAL --SEL_AGE $LEPHAREDIR/examples/AGE_BC03COMB.dat
mag_gal  -c HERSCHEL.para -t G --GAL_LIB_IN LIB_BC03CAL --GAL_LIB_OUT BC_COSMOS  --MOD_EXTINC 1,14,1,14 --EXTINC_LAW SB_calzetti.dat,extlaw_0.9.dat --EB_V 0.,0.1,0.2,0.3,0.4,0.5,0.6,0.7  --EM_LINES PHYS --EM_DISPERSION 1 --ADD_DUSTEM NO

# Fit in FIR
zphota -c HERSCHEL.para --CAT_IN $LEPHAREDIR/examples/MIPS.in --CAT_OUT lumFIR.out --ZPHOTLIB BC_COSMOS  --ADD_EMLINES 0,100 --AUTO_ADAPT NO  --ZFIX YES --FIR_LIB DALE_COSMOS  --FIR_SUBSTELLAR YES  --FIR_FREESCALE YES  --FIR_CONT 8257536

# Fit in FIR with SED in output
zphota -c HERSCHEL.para --CAT_IN $LEPHAREDIR/examples/MIPS.in --CAT_OUT testFIR.out --ZPHOTLIB BC_COSMOS  --ADD_EMLINES 0,100 --AUTO_ADAPT NO  --ZFIX YES --FIR_LIB DALE_COSMOS  --FIR_SUBSTELLAR YES  --FIR_FREESCALE YES  --FIR_CONT 8257536 --CAT_LINES 11980,12010 --SPEC_OUT YES

# Plot the best-fit templates
# Results in MULTISPEC.pdf
python $LEPHAREDIR/examples/spec.py Id*spec -d pdf



#########################################################
# EXTINCTION
#########################################################


filter -c COSMOS.para  --FILTER_LIST cosmos/u_cfht.lowres,cosmos/B_subaru.lowres,cosmos/V_subaru.lowres,cosmos/r_subaru.lowres,cosmos/i_subaru.lowres,cosmos/suprime_FDCCD_z.res,vista/Y.lowres,vista/J.lowres,vista/H.lowres,vista/K.lowres --FILTER_CALIB 0 --FILTER_FILE filter_extinc
# Read the filters and compute extinctions
filter_extinc -c COSMOS.para --FILTER_FILE filter_extinc.dat

